[field]
pg1-path=/validation/source-data
pg1-port=5432
pg1-socket-path=/var/run/postgresql

[global]
repo1-path=/validation/repository
repo1-retention-full=2
spool-path=/validation/spool
lock-path=/validation/lock
log-path=/validation/log
process-max=2
start-fast=y
log-level-console=info
log-level-file=off

[global:archive-push]
compress-level=3
