[demo]
pg1-path=/var/lib/pgdrill-demo/pgbackrest/source-data
pg1-port=5433
pg1-socket-path=/var/run/postgresql

[global]
repo1-path=/mnt/pgdrill-repository/pgbackrest/repository
repo1-retention-full=2
spool-path=/var/lib/pgdrill-demo/pgbackrest/spool
lock-path=/var/lib/pgdrill-demo/pgbackrest/lock
log-path=/var/lib/pgdrill-demo/pgbackrest/log
process-max=2
start-fast=y
log-level-console=info
log-level-file=off

[global:archive-push]
compress-level=3
