[demo]

[global]
repo1-path=/mnt/pgdrill-repository/pgbackrest/repository
spool-path=/var/lib/pgdrill-demo/pgbackrest/spool
lock-path=/var/lib/pgdrill-demo/pgbackrest/lock
log-path=/var/lib/pgdrill-demo/pgbackrest/log
process-max=2
log-level-console=info
log-level-file=off
