[barman]
barman_user = postgres
configuration_files_directory = /validation/barman.d
barman_home = /validation/barman
barman_lock_directory = /validation/barman/locks
log_file = /validation/barman/barman.log
log_level = INFO
