[field]
description = pgdrill disposable Barman field repository
active = true
conninfo = host=/var/run/postgresql port=5432 user=postgres dbname=postgres
backup_method = local-rsync
archiver = on
streaming_archiver = off
path_prefix = /usr/lib/postgresql/18/bin
immediate_checkpoint = true
minimum_redundancy = 1
